---
title: Kyle Tress
description: The personal website of Olympic skeleton athlete Kyle Tress
url: https://tress.siteleaf.net
timezone: America/New_York
include: ['_pages']
collections:
  books:
    title: Books
    output: true
    layout: book
  notes:
    title: Notes
    output: true
  faqs:
    title: Skeleton Faqs
  newsletters:
    title: Newsletters
    output: true
    permalink: "/newsletters/:title"
    layout: newsletter
  uploads:
    title: Uploads
    output: true
  highlights:
    title: Highlights
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
    type: books
  values:
    layout: book
    permalink: "/reading/:title"
- scope:
    path: ''
    type: newsletters
  values:
    layout: newsletter
    permalink: "/newsletters/:title/"
permalink: /:title/
username: kyletress
email: kyle@kyletress.com
ga: UA-1619676-7
quote: Mens sana in corpore sano
typekit_id: oia2txu
youtube: jktress
sass:
  style: compressed
markdown: redcarpet
redcarpet:
  extensions:
  - autolink
  - fenced_code_blocks
  - lax_spacing
  - strikethrough
  - superscript
  - tables
  - footnotes
  - highlight
